INSERT INTO stock (symbol, company_name, sector, description) VALUES
('STYLERS', 'Stylers International Limited', 'TEXTILE COMPOSITE', 'Stylers International Limited got listed on the exchange pursuant to the Scheme of Arrangement for merger/ amalgamation of AEL Textiles Limited (AEL). STYLERS was incorporated in Pakistan as a private limited company under the repealed Companies Ordiance, 1984 (now Companies Act, 2017) on 27 Nov, 1991 and was converted into public limited company from 21 May, 2021. The company is principally engaged in carrying out manufacturing, marketing and export of ready-made garments.'),
('FDIBL', 'First Dawood Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'First Dawood Investment Bank Limited is a financial institution specializing in investment banking and securities services, providing a range of financial solutions.'),
('FECM', 'First Elite Capital Modaraba', 'MODARABAS', 'First Elite Capital Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FECTC', 'Fecto Cement Limited', 'CEMENT', 'Fecto Cement Limited is a significant player in the cement industry, producing high-quality cement for construction and infrastructure projects.'),
('FEM', 'First Equity Modaraba', 'MODARABAS', 'First Equity Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FEROZ', 'Ferozsons Laboratories Limited', 'PHARMACEUTICALS', 'Ferozsons Laboratories Limited is a pharmaceutical company known for its research, development, and production of a wide range of pharmaceutical products.'),
('FFBL', 'Fauji Fertilizer Bin Qasim Limited', 'FERTILIZER', 'Fauji Fertilizer Bin Qasim Limited is a major player in the fertilizer industry, producing a range of fertilizers for agriculture and related applications.'),
('FFC', 'Fauji Fertilizer Company Limited', 'FERTILIZER', 'Fauji Fertilizer Company Limited is a leading player in the fertilizer industry, producing a range of fertilizers for agriculture and related applications.'),
('FFL', 'Fauji Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Fauji Foods Limited is a company in the food and personal care products sector, producing a variety of dairy and food products.'),
('FFLM', 'First Fidelity Leasing Modaraba', 'MODARABAS', 'First Fidelity Leasing Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FHAM', 'First Habib Modaraba', 'MODARABAS', 'First Habib Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FIBLM', 'First IBL Modaraba', 'MODARABAS', 'First IBL Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FIL', 'Fateh Industries Limited', 'LEATHER & TANNERIES', 'Fateh Industries Limited is engaged in the leather and tanneries industry, producing leather and related products.'),
('FIM', 'First Investec Modaraba', 'MODARABAS', 'First Investec Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FIMM', 'First Imrooz Modaraba', 'MODARABAS', 'First Imrooz Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FLYNG', 'Flying Cement Company Limited', 'CEMENT', 'Flying Cement Company Limited is a significant player in the cement industry, producing high-quality cement for construction and infrastructure projects.'),
('FML', 'Feroze1888 Mills Limited', 'TEXTILE COMPOSITE', 'Feroze1888 Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('FNBM', 'First National Bank Modaraba', 'MODARABAS', 'First National Bank Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FNEL', 'First National Equities Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'First National Equities Limited is a financial company operating in the investment and securities sector, providing a range of financial services and investment opportunities.'),
('FPJM', 'First Punjab Modaraba', 'MODARABAS', 'First Punjab Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FPRM', 'First Paramount Modaraba', 'MODARABAS', 'First Paramount Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FRCL', 'Frontier Ceramics Limited', 'GLASS & CERAMICS', 'Frontier Ceramics Limited is engaged in the glass and ceramics industry, producing a variety of glass and ceramic products.'),
('FRSM', 'Faran Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Faran Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('FSWL', 'Fateh Sports Wear Limited', 'TEXTILE COMPOSITE', 'Fateh Sports Wear Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('FTHM', 'Fateh Textile Mills Limited', 'TEXTILE COMPOSITE', 'Fateh Textile Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('FTMM', 'First Treet Manufacturing Modaraba', 'MODARABAS', 'First Treet Manufacturing Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FTSM', 'First Tri-Star Modaraba', 'MODARABAS', 'First Tri-Star Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FUDLM', 'First UDL Modaraba', 'MODARABAS', 'First UDL Modaraba is a modaraba engaged in various financial and investment activities, providing Sharia-compliant financial services.'),
('FZCM', 'Fazal Cloth Mills Limited', 'TEXTILE COMPOSITE', 'Fazal Cloth Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('GADT', 'Gadoon Textile Mills Limited', 'TEXTILE SPINNING', 'Gadoon Textile Mills Limited is a significant player in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('GAL', 'Ghandhara Automobiles Limited', 'AUTOMOBILE ASSEMBLER', 'Ghandhara Automobiles Limited is engaged in the assembly and manufacturing of automobiles and related products.'),
('GAMON', 'Gammon Pakistan Limited', 'MISCELLANEOUS', 'Gammon Pakistan Limited is a company in the miscellaneous sector, involved in various industrial and business activities.'),
('GATI', 'Gatron (Industries) Limited', 'SYNTHETIC & RAYON', 'Gatron (Industries) Limited is engaged in the synthetic and rayon industry, producing synthetic fibers for various applications.'),
('GATM', 'Gul Ahmed Textile Mills Limited', 'TEXTILE COMPOSITE', 'Gul Ahmed Textile Mills Limited is a leading company in the textile composite industry, producing a variety of textile products for domestic and international markets.'),
('GCIL', 'Ghani Chemical Industries Limited', 'CHEMICAL', 'Ghani Chemical Industries Limited is engaged in the chemical industry, producing a range of chemical products for various applications.'),
('GEMPAPL', 'Pak Agro Packaging Limited(GEM)', 'PAPER & BOARD', 'Pak Agro Packaging Limited (GEM) is a company in the paper and board industry, manufacturing packaging materials for the agriculture sector.'),
('GEMSPNL', 'Supernet Limited', 'TECHNOLOGY & COMMUNICATION', 'Supernet Limited is a company in the technology and communication sector, providing network and communication services.'),
('GEMUNSL', 'Universal Network Systems Limited(GEM)', 'TRANSPORT', 'Universal Network Systems Limited (GEM) is a company in the transport sector, providing logistics and transportation services.'),
('GFIL', 'Ghazi Fabrics International Limited', 'TEXTILE COMPOSITE', 'Ghazi Fabrics International Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('GGGL', 'Ghani Global Glass Limited', 'GLASS & CERAMICS', 'Ghani Global Glass Limited is engaged in the glass and ceramics industry, producing a variety of glass products for various applications.'),
('GGL', 'Ghani Global Holdings Limited', 'CHEMICAL', 'Ghani Global Holdings Limited is engaged in the chemical industry, producing a range of chemical products for various applications.'),
('GHGL', 'Ghani Glass Limited', 'GLASS & CERAMICS', 'Ghani Glass Limited is engaged in the glass and ceramics industry, producing a variety of glass products for various applications.'),
('GHNI', 'Ghandhara Industries Limited', 'AUTOMOBILE ASSEMBLER', 'Ghandhara Industries Limited is engaged in the assembly and manufacturing of automobiles and related products.'),
('GIL', 'Good Luck Industries Ltd.', 'FOOD & PERSONAL CARE PRODUCTS', 'Good Luck Industries Ltd. is involved in the food and personal care products industry, producing a variety of consumer goods.'),
('GLAXO', 'GlaxoSmithKline Pakistan Limited', 'PHARMACEUTICALS', 'GlaxoSmithKline Pakistan Limited is a major player in the pharmaceutical industry, producing a range of pharmaceutical and healthcare products.'),
('GLOT', 'Globe Textile Mills Limited', 'TEXTILE SPINNING', 'Globe Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('GLPL', 'Gillette Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Gillette Pakistan Limited is involved in the food and personal care products industry, producing a variety of consumer goods.'),
('GOC', 'GOC (Pak) Limited.', 'MISCELLANEOUS', 'GOC (Pak) Limited is a company in the miscellaneous sector, involved in various industrial and business activities.'),
('GRR', 'Globe Residency Reit', 'REAL ESTATE INVESTMENT TRUST', 'Globe Residency Reit is a real estate investment trust (REIT) focused on investment in real estate properties, providing income to its investors through dividends.'),
('GRYL', 'Grays Leasing Limited', 'LEASING COMPANIES', 'Grays Leasing Limited is a company in the leasing industry, providing financial leasing services for various assets and equipment.'),
('GSPM', 'Gulshan Spinning Mills Limited', 'TEXTILE SPINNING', 'Gulshan Spinning Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('GTYR', 'Ghandhara Tyre & Rubber Company Limited', 'AUTOMOBILE PARTS & ACCESSORIES', 'Ghandhara Tyre & Rubber Company Limited is engaged in the manufacturing of automobile tires and rubber products.'),
('GUSM', 'Gulistan Spinning Mills Limited', 'TEXTILE SPINNING', 'Gulistan Spinning Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('GUTM', 'Gulistan Textile Mills Limited', 'TEXTILE SPINNING', 'Gulistan Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('GVGL', 'Ghani Value Glass Limited', 'GLASS & CERAMICS', 'Ghani Value Glass Limited is engaged in the glass and ceramics industry, producing a variety of glass products for various applications.'),
('GWLC', 'Gharibwal Cement Limited', 'CEMENT', 'Gharibwal Cement Limited is a significant player in the cement industry, producing high-quality cement for construction and infrastructure projects.'),
('HABSM', 'Habib Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Habib Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('HADC', 'Haydari Construction Company Limited', 'MISCELLANEOUS', 'Haydari Construction Company Limited is a company in the miscellaneous sector, involved in various construction and infrastructure projects.'),
('HAEL', 'Hala Enterprises Limited', 'TEXTILE COMPOSITE', 'Hala Enterprises Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('HAFL', 'Hafiz Limited', 'TEXTILE COMPOSITE', 'Hafiz Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('HAJT', 'Hajra Textile Mills Limited', 'TEXTILE SPINNING', 'Hajra Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('HALEON', 'Haleon Pakistan Limited', 'PHARMACEUTICALS', 'Haleon Pakistan Limited is engaged in the pharmaceutical industry, producing a range of pharmaceutical products for various medical applications.'),
('HASCOL', 'Hascol Petroleum Limited', 'OIL & GAS MARKETING COMPANIES', 'Hascol Petroleum Limited is a major player in the oil and gas marketing sector, involved in the distribution and marketing of petroleum and related products.'),
('HATM', 'Hamid Textile Mills Limited', 'TEXTILE COMPOSITE', 'Hamid Textile Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('HBL', 'Habib Bank Limited', 'COMMERCIAL BANKS', 'Habib Bank Limited is one of the largest commercial banks in Pakistan, providing a range of banking and financial services to individuals, businesses, and institutions.'),
('HBLTETF', 'HBL Total Treasury (ETF)', 'EXCHANGE TRADED FUNDS', 'HBL Total Treasury (ETF) is an exchange-traded fund (ETF) focused on investing in treasury and money market instruments, providing investors with a diversified and low-risk investment option.'),
('HCAR', 'Honda Atlas Cars (Pakistan) Limited', 'AUTOMOBILE ASSEMBLER', 'Honda Atlas Cars (Pakistan) Limited is engaged in the assembly and manufacturing of automobiles, particularly Honda cars and related products.'),
('HCL', 'Hallmark Company Limited', 'TECHNOLOGY & COMMUNICATION', 'Hallmark Company Limited is a company in the technology and communication sector, involved in various industrial and business activities.'),
('HGFA', 'HBL Growth Fund', 'CLOSE - END MUTUAL FUND', 'HBL Growth Fund is a close-end mutual fund managed by HBL Asset Management Limited, providing investors with an opportunity to participate in the growth of the Pakistani capital market.'),
('HICL', 'Habib Insurance Company Limited', 'INSURANCE', 'Habib Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services to individuals and businesses.'),
('HIFA', 'HBL Investment Fund', 'CLOSE - END MUTUAL FUND', 'HBL Investment Fund is a close-end mutual fund managed by HBL Asset Management Limited, providing investors with a diversified and professionally managed investment portfolio.'),
('HINO', 'Hinopak Motors Limited', 'AUTOMOBILE ASSEMBLER', 'Hinopak Motors Limited is engaged in the assembly and manufacturing of Hino buses and trucks, catering to the transportation and logistics sector.'),
('HINOON', 'Highnoon Laboratories Limited', 'PHARMACEUTICALS', 'Highnoon Laboratories Limited is a pharmaceutical company known for its research, development, and production of a wide range of pharmaceutical products.'),
('HIRAT', 'Hira Textile Mills Limited', 'TEXTILE SPINNING', 'Hira Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('HKKT', 'Hakkim Textile Mills Limited', 'TEXTILE WEAVING', 'Hakkim Textile Mills Limited is a company in the textile weaving industry, involved in the production of a variety of woven textile products.'),
('HMB', 'Habib Metropolitan Bank Limited', 'COMMERCIAL BANKS', 'Habib Metropolitan Bank Limited is a commercial bank providing a range of banking and financial services to individuals, businesses, and institutions.'),
('HMIM', 'Haji Mohammad Ismail Mills Limited', 'TEXTILE SPINNING', 'Haji Mohammad Ismail Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('HPL', 'Hoechst Pakistan Limited', 'PHARMACEUTICALS', 'Hoechst Pakistan Limited is engaged in the pharmaceutical industry, producing a range of pharmaceutical and healthcare products.'),
('HRPL', 'Habib Rice Product Limited.', 'SUGAR & ALLIED INDUSTRIES', 'Habib Rice Product Limited is engaged in the sugar and allied industries, producing rice and related products.'),
('HSPI', 'Huffaz Seamless Pipe Industries Limited', 'ENGINEERING', 'Huffaz Seamless Pipe Industries Limited is engaged in the engineering industry, particularly in the manufacturing of seamless pipes for various applications.'),
('HTL', 'Hi-Tech Lubricants Limited', 'OIL & GAS MARKETING COMPANIES', 'Hi-Tech Lubricants Limited is a company in the oil and gas marketing sector, involved in the distribution and marketing of lubricants and related products.'),
('HUBC', 'The Hub Power Company Limited', 'POWER GENERATION & DISTRIBUTION', 'The Hub Power Company Limited is a major player in the power generation and distribution sector, contributing to the generation of electricity for the national grid.'),
('HUMNL', 'Hum Network Limited', 'TECHNOLOGY & COMMUNICATION', 'Hum Network Limited is a company in the technology and communication sector, particularly in the media and entertainment industry, providing a variety of content and services.'),
('HUSI', 'Husein Industries Limited', 'TEXTILE COMPOSITE', 'Husein Industries Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('HWQS', 'Haseeb Waqas Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Haseeb Waqas Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('IBFL', 'Ibrahim Fibres Limited', 'SYNTHETIC & RAYON', 'Ibrahim Fibres Limited is a company in the synthetic and rayon industry, producing a variety of synthetic fibers and related products.'),
('IBLHL', 'IBL HealthCare Limited', 'PHARMACEUTICALS', 'IBL HealthCare Limited is engaged in the pharmaceutical industry, producing a range of pharmaceutical and healthcare products.'),
('ICCI', 'ICC Industries Limited', 'TEXTILE WEAVING', 'ICC Industries Limited is a company in the textile weaving industry, involved in the production of a variety of woven textile products.'),
('ICIBL', 'Invest Capital Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Invest Capital Investment Bank Limited is engaged in the investment banking and securities industry, providing financial services and investment solutions.'),
('ICL', 'Ittehad Chemicals Limted', 'CHEMICAL', 'Ittehad Chemicals Limited is engaged in the chemical industry, producing a range of chemical products for various applications.'),
('IDRT', 'Idrees Textile Mills Limited', 'TEXTILE SPINNING', 'Idrees Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('IDSM', 'Ideal Spinning Mills Limited', 'TEXTILE SPINNING', 'Ideal Spinning Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('IDYM', 'Indus Dyeing & Manufacturing Co. Limited', 'TEXTILE SPINNING', 'Indus Dyeing & Manufacturing Co. Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('IGIHL', 'IGI Holdings Limited', 'INSURANCE', 'IGI Holdings Limited is engaged in the insurance industry, providing a range of insurance products and services to individuals and businesses.'),
('IGIL', 'IGI Life Insurance Limited', 'INSURANCE', 'IGI Life Insurance Limited is engaged in the life insurance industry, providing a variety of life insurance products and services to individuals and families.'),
('ILP', 'Interloop Limited', 'TEXTILE COMPOSITE', 'Interloop Limited is a company in the textile composite industry, involved in the production of a variety of textile products, particularly socks and hosiery items.'),
('IMAGE', 'Image Pakistan Limited', 'SYNTHETIC & RAYON', 'Image Pakistan Limited is engaged in the synthetic and rayon industry, producing a variety of synthetic fibers and related products.'),
('IML', 'Imperial  Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Imperial Limited is engaged in the investment banking and securities industry, providing financial services and investment solutions.'),
('INDU', 'Indus Motor Company Limited', 'AUTOMOBILE ASSEMBLER', 'Indus Motor Company Limited is a major player in the automobile industry, particularly in the assembly and manufacturing of Toyota vehicles and related products.'),
('INIL', 'International Industries Limited', 'ENGINEERING', 'International Industries Limited is a company in the engineering industry, producing a variety of industrial and engineering products for domestic and international markets.'),
('INKL', 'International Knitwear Limited', 'TEXTILE COMPOSITE', 'International Knitwear Limited is a company in the textile composite industry, involved in the production of a variety of knitwear and related products.'),
('INMF', 'Investec Mutual Fund Limited', 'CLOSE - END MUTUAL FUND', 'Investec Mutual Fund Limited is a close-end mutual fund offering investors an opportunity to participate in the performance of the Pakistani capital market.'),
('ISIL', 'Ismail Industries Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Ismail Industries Limited is involved in the food and personal care products industry, producing a variety of consumer goods, particularly confectionery items.'),
('ISL', 'International Steels Limited', 'ENGINEERING', 'International Steels Limited is a company in the engineering industry, particularly in the production of high-quality steel products for various applications.'),
('ITTEFAQ', 'Ittefaq Iron Industries Limited', 'ENGINEERING', 'Ittefaq Iron Industries Limited is engaged in the engineering industry, particularly in the manufacturing of iron and steel products for construction and industrial use.'),
('JATM', 'J.A. Textile Mills Limited', 'TEXTILE SPINNING', 'J.A. Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('JDMT', 'Janana De Malucho Textile Mills Limited', 'TEXTILE SPINNING', 'Janana De Malucho Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('JDWS', 'JDW Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'JDW Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('JGICL', 'Jubilee General Insurance Limited', 'INSURANCE', 'Jubilee General Insurance Limited is engaged in the general insurance industry, providing a range of insurance products and services to individuals and businesses.'),
('JKSM', 'J.K. Spinning Mills Limited', 'TEXTILE SPINNING', 'J.K. Spinning Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('JLICL', 'Jubilee Life Insurance Company Limited', 'INSURANCE', 'Jubilee Life Insurance Company Limited is a prominent player in the insurance industry, providing a range of life insurance products and services.'),
('JOPP', 'Johnson & Phillips (Pakistan) Limited', 'CABLE & ELECTRICAL GOODS', 'Johnson & Phillips (Pakistan) Limited is engaged in the manufacturing of cables and electrical goods for various applications.'),
('JSBL', 'JS Bank Limited', 'COMMERCIAL BANKS', 'JS Bank Limited is a commercial bank providing a range of banking and financial services to individuals, businesses, and corporate clients.'),
('JSCL', 'Jahangir Siddiqui & Co. Ltd.', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Jahangir Siddiqui & Co. Ltd. is a company engaged in investment banking and securities services, providing a range of financial solutions.'),
('JSCLPSA', 'Jahangir Sidd(Pref)', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Jahangir Siddiqui (Preferred) is a preferred stock of Jahangir Siddiqui & Co. Ltd., representing ownership in the company with certain preferential rights.'),
('JSGBETF', 'JS Global Banking Sector(ETF)', 'EXCHANGE TRADED FUNDS', 'JS Global Banking Sector Exchange Traded Fund (ETF) is an investment fund that holds a portfolio of stocks in the banking sector, providing investors with exposure to this specific market segment.'),
('JSGCL', 'JS Global Capital Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'JS Global Capital Limited is a financial institution engaged in investment banking and securities services, providing a range of financial solutions.'),
('JSIL', 'JS Investments Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'JS Investments Limited is a company operating in the investment and securities sector, providing a variety of investment solutions and financial services.'),
('JSMFETF', 'JS Momentum Factor Exchange Traded Fund', 'EXCHANGE TRADED FUNDS', 'JS Momentum Factor Exchange Traded Fund is an investment fund that aims to track the performance of high-momentum stocks, providing investors with exposure to this specific investment strategy.'),
('JSML', 'Jauharabad Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Jauharabad Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('JUBS', 'Jubilee Spinning & Weaving Mills Ltd.', 'TEXTILE COMPOSITE', 'Jubilee Spinning & Weaving Mills Ltd. is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('JVDC', 'Javedan Corporation Limited', 'PROPERTY', 'Javedan Corporation Limited is engaged in the property sector, with a focus on real estate development and related activities.'),
('JVDCPS', 'Javedan Corporation (Pref)', 'CEMENT', 'Javedan Corporation (Preferred) is a preferred stock of Javedan Corporation Limited, representing ownership in the company with certain preferential rights.'),
('KAKL', 'Kaiser Arts & Krafts Limited', 'TEXTILE COMPOSITE', 'Kaiser Arts & Krafts Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('KAPCO', 'Kot Addu Power Company Limited', 'POWER GENERATION & DISTRIBUTION', 'Kot Addu Power Company Limited is a significant player in the power generation and distribution industry, providing electricity to the national grid.'),
('KCL', 'Karam Ceramics Limited', 'GLASS & CERAMICS', 'Karam Ceramics Limited is engaged in the manufacturing of ceramics and glass products for various applications.'),
('KEL', 'K-Electric Limited', 'POWER GENERATION & DISTRIBUTION', 'K-Electric Limited is a major player in the power generation and distribution industry, providing electricity to consumers in Karachi and adjoining areas.'),
('KHTC', 'Khyber Tobacco Company Limited', 'TOBACCO', 'Khyber Tobacco Company Limited is engaged in the production and marketing of tobacco products, catering to domestic and international markets.'),
('KHYT', 'Khyber Textile Mills Limited', 'TEXTILE COMPOSITE', 'Khyber Textile Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('KML', 'Kohinoor Mills Limited', 'TEXTILE COMPOSITE', 'Kohinoor Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('KOHC', 'Kohat Cement Company Limited', 'CEMENT', 'Kohat Cement Company Limited is a significant player in the cement industry, producing high-quality cement for construction and infrastructure projects.'),
('KOHE', 'Kohinoor Energy Limited', 'POWER GENERATION & DISTRIBUTION', 'Kohinoor Energy Limited is a company in the power generation and distribution industry, involved in the production and distribution of electricity.'),
('KOHP', 'Kohinoor Power Company Limited', 'POWER GENERATION & DISTRIBUTION', 'Kohinoor Power Company Limited is a company in the power generation and distribution industry, involved in the production and distribution of electricity.'),
('KOHTM', 'Kohat Textile Mills Limited', 'TEXTILE SPINNING', 'Kohat Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('KOIL', 'Kohinoor Industries Limited', 'TEXTILE COMPOSITE', 'Kohinoor Industries Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('KOSM', 'Kohinoor Spinning Mills Limited', 'TEXTILE SPINNING', 'Kohinoor Spinning Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('KPUS', 'Khairpur Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Khairpur Sugar Mills Limited is a company in the sugar and allied industries, producing sugar and related products.'),
('KSBP', 'KSB Pumps Company Limited', 'ENGINEERING', 'KSB Pumps Company Limited is engaged in the engineering industry, manufacturing pumps and related products for various applications.'),
('KSTM', 'Khalid Siraj Textile Mills Limited', 'TEXTILE SPINNING', 'Khalid Siraj Textile Mills Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('KTML', 'Kohinoor Textile Mills Limited', 'TEXTILE COMPOSITE', 'Kohinoor Textile Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('LCI', 'Lucky Core Industries Limited', 'CHEMICAL', 'Lucky Core Industries Limited is a company in the chemical industry, producing a range of chemical products for various applications.'),
('LEUL', 'Leather Up Limited', 'LEATHER & TANNERIES', 'Leather Up Limited is engaged in the leather and tanneries industry, producing a variety of leather products for domestic and international markets.'),
('LMSM', 'Landmark Spinning Industries Limited', 'TEXTILE SPINNING', 'Landmark Spinning Industries Limited is a company in the textile spinning industry, known for its production of high-quality yarns and textile products.'),
('LOADS', 'Loads Limited', 'AUTOMOBILE PARTS & ACCESSORIES', 'Loads Limited is engaged in the manufacturing of automobile parts and accessories, providing solutions for various automotive applications.'),
('LOTCHEM', 'Lotte Chemical Pakistan Limited', 'CHEMICAL', 'Lotte Chemical Pakistan Limited is a major player in the chemical industry, producing a variety of chemical products for domestic and international markets.'),
('LPGL', 'Leiner Pak Gelatine Limited', 'CHEMICAL', 'Leiner Pak Gelatine Limited is engaged in the chemical industry, manufacturing gelatine products for various applications.'),
('LPL', 'Lalpir Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Lalpir Power Limited is a company in the power generation and distribution industry, involved in the production and distribution of electricity.'),
('LSEPL', 'LSE Proptech Limited', 'TECHNOLOGY & COMMUNICATION', 'LSE Proptech Limited is engaged in the technology and communication sector, providing solutions and services related to property technology.'),
('LSEVL', 'LSE Ventures Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'LSE Ventures Limited is involved in investment banking and securities services, providing financial solutions and services to clients.'),
('LUCK', 'Lucky Cement Limited', 'CEMENT', 'Lucky Cement Limited is a major player in the cement industry, producing high-quality cement for construction and infrastructure projects.'),
('MACFL', 'MACPAC Films Limited', 'MISCELLANEOUS', 'MACPAC Films Limited is engaged in the production of films and related products, catering to various industries and applications.'),
('MACTER', 'Macter International Limited', 'PHARMACEUTICALS', 'Macter International Limited is a company in the pharmaceuticals industry, producing a range of pharmaceutical products for domestic and international markets.'),
('MARI', 'Mari Petroleum Company Limited', 'OIL & GAS EXPLORATION COMPANIES', 'Mari Petroleum Company Limited is involved in the exploration and production of oil and gas, contributing to the energy sector.'),
('MCB', 'MCB Bank Limited', 'COMMERCIAL BANKS', 'MCB Bank Limited is a commercial bank providing a range of banking and financial services to individuals, businesses, and corporate clients.'),
('MCBIM', 'MCB Investment Management Limited.', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'MCB Investment Management Limited is engaged in investment management and securities services, providing a variety of financial solutions.'),
('MDTL', 'Media Times Limited', 'TECHNOLOGY & COMMUNICATION', 'Media Times Limited is involved in the technology and communication sector, providing media-related products and services.'),
('MEBL', 'Meezan Bank Limited', 'COMMERCIAL BANKS', 'Meezan Bank Limited is a commercial bank providing Shariah-compliant banking and financial services to individuals and businesses.'),
('MEHT', 'Mehmood Textile Mills Limited', 'TEXTILE COMPOSITE', 'Mehmood Textile Mills Limited is a company in the textile composite industry, involved in the production of a variety of textile products.'),
('MERIT', 'Merit Packaging Limited', 'PAPER & BOARD', 'Merit Packaging Limited is engaged in the manufacturing of paper and board products, catering to various industries and applications.'),
('META', 'MetaTech Trading Limited', 'MISCELLANEOUS', 'MetaTech Trading Limited is involved in miscellaneous business activities, providing products and services across various sectors.'),
('MFFL', 'Mitchells Fruit Farms Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Mitchells Fruit Farms Limited is engaged in the production of fruit-based products and beverages, contributing to the food and personal care industry.'),
('MFL', 'Matco Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Matco Foods Limited is a company in the food and personal care products industry, producing a variety of food items and personal care products.'),
('MFTM', 'Mohammad Farooq Textile Mills Limited', 'TEXTILE COMPOSITE', 'Mohammad Farooq Textile Mills Limited operates in the textile composite industry, manufacturing a variety of textile products.'),
('MIRKS', 'Mirpurkhas Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Mirpurkhas Sugar Mills Limited is engaged in the sugar and allied industries, producing sugar and related products.'),
('MLCF', 'Maple Leaf Cement Factory Limited', 'CEMENT', 'Maple Leaf Cement Factory Limited is a major player in the cement industry, manufacturing high-quality cement for construction and infrastructure projects.'),
('MODAM', 'Modaraba Al-Mali', 'MODARABAS', 'Modaraba Al-Mali is a modaraba company providing financial and investment services according to Islamic principles.'),
('MOHE', 'Mohib Exports Limited', 'TEXTILE WEAVING', 'Mohib Exports Limited is involved in textile weaving, producing a variety of woven textile products for domestic and international markets.'),
('MQTM', 'Maqbool Textile Mills Limited', 'TEXTILE SPINNING', 'Maqbool Textile Mills Limited operates in the textile spinning industry, manufacturing quality yarns for various applications.'),
('MRNS', 'Mehran Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Mehran Sugar Mills Limited is engaged in the sugar and allied industries, producing sugar and related products.'),
('MSCL', 'Metropolitan Steel Corporation Limited', 'ENGINEERING', 'Metropolitan Steel Corporation Limited is involved in the engineering sector, manufacturing steel products for construction and industrial applications.'),
('MSOT', 'Masood Textile Mills Limited', 'TEXTILE COMPOSITE', 'Masood Textile Mills Limited operates in the textile composite industry, producing a variety of textile products for different market segments.'),
('MSOTPS', 'Masood Textile (Pref)', 'TEXTILE COMPOSITE', 'Masood Textile (Preferred) shares belong to the textile composite industry and represent preferred stock in Masood Textile Mills Limited.'),
('MTL', 'Millat Tractors Limited', 'AUTOMOBILE ASSEMBLER', 'Millat Tractors Limited is a major player in the automobile assembly industry, manufacturing tractors and agricultural machinery.'),
('MUBT', 'Mubarak Textile Mills Limited', 'TEXTILE COMPOSITE', 'Mubarak Textile Mills Limited operates in the textile composite industry, manufacturing a variety of textile products.'),
('MUGHAL', 'Mughal Iron & Steel Industries Limited', 'ENGINEERING', 'Mughal Iron & Steel Industries Limited is involved in the engineering sector, manufacturing iron and steel products for construction and industrial use.'),
('MUREB', 'Murree Brewery Company Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Murree Brewery Company Limited is a major player in the food and personal care products industry, producing a variety of beverages.'),
('MWMP', 'Mandviwala Mauser Plastic Industries', 'MISCELLANEOUS', 'Mandviwala Mauser Plastic Industries is involved in miscellaneous business activities, providing plastic products for various applications.'),
('MZNPETF', 'Meezan Pakistan ETF', 'EXCHANGE TRADED FUNDS', 'Meezan Pakistan ETF is an exchange-traded fund that tracks the performance of the Pakistani financial market, offering investors a diversified investment option.'),
('NAFL', 'National Fibres Limited', 'SYNTHETIC & RAYON', 'National Fibres Limited operates in the synthetic and rayon industry, manufacturing fibers and related products for various applications.'),
('NAGC', 'Nagina Cotton Mills Limited', 'TEXTILE SPINNING', 'Nagina Cotton Mills Limited operates in the textile spinning industry, producing quality cotton yarns for domestic and international markets.'),
('NATF', 'National Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'National Foods Limited is a major player in the food and personal care products industry, producing a variety of food items and personal care products.'),
('NATM', 'Nadeem Textile Mills Limited', 'TEXTILE SPINNING', 'Nadeem Textile Mills Limited operates in the textile spinning industry, manufacturing quality yarns for various applications.'),
('NBP', 'National Bank of Pakistan', 'COMMERCIAL BANKS', 'National Bank of Pakistan is a leading commercial bank providing a range of banking and financial services to individuals and businesses.'),
('NBPGETF', 'NBP Pakistan Growth ETF', 'EXCHANGE TRADED FUNDS', 'NBP Pakistan Growth ETF is an exchange-traded fund that tracks the growth of the Pakistani financial market, providing investors with exposure to diverse sectors.'),
('NCL', 'Nishat Chunian Limited', 'TEXTILE COMPOSITE', 'Nishat Chunian Limited operates in the textile composite industry, producing a variety of textile products for different market segments.'),
('NCML', 'Nazir Cotton Mills Limited', 'TEXTILE SPINNING', 'Nazir Cotton Mills Limited operates in the textile spinning industry, manufacturing quality cotton yarns for various applications.'),
('NCPL', 'Nishat Chunian Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Nishat Chunian Power Limited is involved in power generation and distribution, contributing to the energy sector.'),
('NESTLE', 'Nestle Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Nestle Pakistan Limited is a major player in the food and personal care products industry, producing a wide range of consumer goods.'),
('NETSOL', 'NetSol Technologies Limited', 'TECHNOLOGY & COMMUNICATION', 'NetSol Technologies Limited is involved in the technology and communication sector, providing software and IT solutions to various industries.'),
('NEXT', 'Next Capital Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Next Capital Limited is engaged in investment banking and securities services, providing financial solutions and services to clients.'),
('NICL', 'Nimir Industrial Chemicals Limited', 'CHEMICAL', 'Nimir Industrial Chemicals Limited is a chemical company producing a range of industrial chemicals for different applications.'),
('NINA', 'Nina Industries Limited', 'TEXTILE COMPOSITE', 'Nina Industries Limited operates in the textile composite industry, producing a variety of textile products for different market segments.'),
('NITGETF', 'NIT Pakistan Gateway ETF', 'EXCHANGE TRADED FUNDS', 'NIT Pakistan Gateway ETF is an exchange-traded fund designed to provide investors with exposure to the growth potential of the Pakistani financial market.'),
('NMFL', 'Nirala MSR Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Nirala MSR Foods Limited is a company in the food and personal care products industry, producing a variety of food items and personal care products.'),
('NML', 'Nishat Mills Limited', 'TEXTILE COMPOSITE', 'Nishat Mills Limited operates in the textile composite industry, producing a variety of textile products for different market segments.'),
('NONS', 'Noon Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Noon Sugar Mills Limited is involved in the sugar and allied industries, producing sugar and related products.'),
('NPL', 'Nishat Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Nishat Power Limited is involved in power generation and distribution, contributing to the energy sector.'),
('NRL', 'National Refinery Limited', 'REFINERY', 'National Refinery Limited operates in the refinery industry, processing crude oil into various petroleum products for domestic and international markets.'),
('NRSL', 'Nimir Resins Limited', 'CHEMICAL', 'Nimir Resins Limited is a chemical company producing resins and related products for industrial applications.'),
('NSRM', 'The National Silk & Rayon Mills Limited', 'SYNTHETIC & RAYON', 'The National Silk & Rayon Mills Limited operates in the synthetic and rayon industry, manufacturing fibers and related products for various applications.'),
('OBOY', 'Oilboy Energy Limited', 'OIL & GAS MARKETING COMPANIES', 'Oilboy Energy Limited operates in the oil and gas marketing industry, providing marketing services for oil and gas products.'),
('OCTOPUS', 'Octopus Digital Limited', 'TECHNOLOGY & COMMUNICATION', 'Octopus Digital Limited is engaged in the technology and communication sector, providing digital services and solutions.'),
('OGDC', 'Oil & Gas Development Company Limited', 'OIL & GAS EXPLORATION COMPANIES', 'Oil & Gas Development Company Limited is a major player in the oil and gas exploration industry, involved in the exploration and production of oil and gas resources.'),
('OLPL', 'OLP Financial Services Pakistan Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'OLP Financial Services Pakistan Limited is engaged in investment banking and securities services, providing financial solutions and services to clients.'),
('OLPM', 'OLP Modaraba', 'MODARABAS', 'OLP Modaraba is a modaraba company providing financial and investment services according to Islamic principles.'),
('OML', 'Olympia Mills Limited', 'MISCELLANEOUS', 'Olympia Mills Limited operates in the miscellaneous sector, involved in various business activities.'),
('ORM', 'Orient Rental Mod', 'MODARABAS', 'Orient Rental Mod is a modaraba company providing financial and investment services according to Islamic principles.'),
('OTSU', 'Otsuka Pakistan Limited', 'PHARMACEUTICALS', 'Otsuka Pakistan Limited is engaged in the pharmaceuticals industry, manufacturing and marketing pharmaceutical products.'),
('PABC', 'Pakistan Aluminium Beverage Cans Limited', 'MISCELLANEOUS', 'Pakistan Aluminium Beverage Cans Limited is involved in the miscellaneous sector, manufacturing aluminum beverage cans for the beverage industry.'),
('PACE', 'Pace (Pakistan) Limited', 'PROPERTY', 'Pace (Pakistan) Limited operates in the property sector, involved in real estate development and property management.'),
('PAEL', 'Pak Elektron Limited', 'CABLE & ELECTRICAL GOODS', 'Pak Elektron Limited is a major player in the cable and electrical goods industry, manufacturing and distributing electrical and electronic products.'),
('PAKD', 'Pak Datacom Limited', 'TECHNOLOGY & COMMUNICATION', 'Pak Datacom Limited is engaged in the technology and communication sector, providing data communication and networking services.'),
('PAKL', 'Pak Leather Crafts Limited', 'LEATHER & TANNERIES', 'Pak Leather Crafts Limited operates in the leather and tanneries industry, manufacturing leather products for various applications.'),
('PAKOXY', 'Pakistan Oxygen Limited', 'CHEMICAL', 'Pakistan Oxygen Limited is involved in the chemical industry, manufacturing and supplying industrial and medical gases.'),
('PAKRI', 'Pakistan Reinsurance Company Limited', 'INSURANCE', 'Pakistan Reinsurance Company Limited is engaged in the insurance industry, providing reinsurance services to insurance companies.'),
('PAKT', 'Pakistan Tobacco Company Limited', 'TOBACCO', 'Pakistan Tobacco Company Limited is a major player in the tobacco industry, manufacturing and marketing tobacco products.'),
('PASL', 'Pervez Ahmed Consultancy Services Ltd.', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Pervez Ahmed Consultancy Services Ltd. is engaged in investment banking and securities services, providing financial consultancy services to clients.'),
('PASM', 'Paramount Spinning Mills Limited', 'TEXTILE COMPOSITE', 'Paramount Spinning Mills Limited operates in the textile composite industry, producing a variety of textile products for different market segments.'),
('PCAL', 'Pakistan Cables Limited', 'CABLE & ELECTRICAL GOODS', 'Pakistan Cables Limited is a major player in the cable and electrical goods industry, manufacturing and distributing a variety of cables and electrical products.'),
('PECO', 'Pakistan Engineering Company Limited', 'ENGINEERING', 'Pakistan Engineering Company Limited is involved in the engineering sector, manufacturing engineering products and services.'),
('PELPS', 'Pak Elektron (Pref)', 'CABLE & ELECTRICAL GOODS', 'Pak Elektron (Preferred) shares belong to the cable and electrical goods industry, representing preferred stock in Pak Elektron Limited.'),
('PGLC', 'Pak-Gulf Leasing Company Limited', 'LEASING COMPANIES', 'Pak-Gulf Leasing Company Limited is engaged in the leasing industry, providing leasing services to individuals and businesses.'),
('PHDL', 'Pakistan Hotels Developers Limited', 'MISCELLANEOUS', 'Pakistan Hotels Developers Limited operates in the miscellaneous sector, involved in various business activities related to hotels and development.'),
('PIAA', 'Pakistan International Airlines Corp', 'TRANSPORT', 'Pakistan International Airlines Corp is a major player in the transport industry, providing airline services for passengers and cargo.'),
('PIAB', 'Pakistan International Airlines Corporat', 'TRANSPORT', 'Pakistan International Airlines Corporation is engaged in the transport industry, providing airline services for passengers and cargo.'),
('PIBTL', 'Pakistan International Bulk Terminal', 'TRANSPORT', 'Pakistan International Bulk Terminal is involved in the transport industry, providing bulk terminal services for handling bulk cargo.'),
('PICL', 'Pakistan Industrial & Commercial Leasing', 'LEASING COMPANIES', 'Pakistan Industrial & Commercial Leasing is engaged in the leasing industry, providing leasing services to individuals and businesses.'),
('PICT', 'Pakistan International Container', 'TRANSPORT', 'Pakistan International Container is involved in the transport industry, providing container services for cargo handling and logistics.'),
('PIL', 'PICIC Insurance Limited', 'INSURANCE', 'PICIC Insurance Limited is engaged in the insurance industry, providing insurance services to individuals and businesses.'),
('PIM', 'Popular Islamic Modaraba', 'MODARABAS', 'Popular Islamic Modaraba is a modaraba company providing financial and investment services according to Islamic principles.'),
('PINL', 'Premier Insurance Limited', 'INSURANCE', 'Premier Insurance Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('PIOC', 'Pioneer Cement Limited', 'CEMENT', 'Pioneer Cement Limited is involved in the cement industry, manufacturing and supplying cement products for construction.'),
('PKGI', 'The Pakistan General Insurance Co. Ltd.', 'INSURANCE', 'The Pakistan General Insurance Co. Ltd. is engaged in the insurance industry, providing general insurance services.'),
('PKGP', 'Pakgen Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Pakgen Power Limited is involved in the power generation and distribution industry, generating and supplying electrical power.'),
('PKGS', 'Packages Limited', 'PAPER & BOARD', 'Packages Limited operates in the paper and board industry, manufacturing and providing packaging solutions.'),
('PMI', 'First Prudential Modaraba', 'MODARABAS', 'First Prudential Modaraba is a modaraba company providing financial and investment services according to Islamic principles.'),
('PMPK', 'Philip Morris (Pakistan) Limited', 'TOBACCO', 'Philip Morris (Pakistan) Limited is involved in the tobacco industry, manufacturing and marketing tobacco products.'),
('PMRS', 'The Premier Sugar Mills', 'SUGAR & ALLIED INDUSTRIES', 'The Premier Sugar Mills is engaged in the sugar and allied industries, producing sugar and related products.'),
('PNSC', 'Pakistan National Shipping Corporation', 'TRANSPORT', 'Pakistan National Shipping Corporation is involved in the transport industry, providing shipping and cargo services.'),
('POL', 'Pakistan Oilfields Limited', 'OIL & GAS EXPLORATION COMPANIES', 'Pakistan Oilfields Limited is a major player in the oil and gas exploration industry, involved in the exploration and production of oil and gas resources.'),
('POML', 'Punjab Oil Mills Limited', 'VANASPATI & ALLIED INDUSTRIES', 'Punjab Oil Mills Limited is engaged in the vanaspati and allied industries, manufacturing and supplying edible oil products.'),
('POWER', 'Power Cement Limited', 'CEMENT', 'Power Cement Limited is involved in the cement industry, manufacturing and supplying cement products for construction.'),
('POWERPS', 'Power Cement (Pref)', 'CEMENT', 'Power Cement (Preferred) shares belong to the cement industry, representing preferred stock in Power Cement Limited.'),
('PPL', 'Pakistan Petroleum Limited', 'OIL & GAS EXPLORATION COMPANIES', 'Pakistan Petroleum Limited is a major player in the oil and gas exploration industry, involved in the exploration and production of oil and gas resources.'),
('PPP', 'Pakistan Paper Products Limited', 'PAPER & BOARD', 'Pakistan Paper Products Limited is involved in the paper and board industry, manufacturing and providing paper and board products.'),
('PPVC', 'Pakistan PVC Limited', 'CHEMICAL', 'Pakistan PVC Limited is engaged in the chemical industry, manufacturing and providing PVC products.'),
('PREMA', 'At-Tahur Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'At-Tahur Limited is involved in the food and personal care products industry, producing a variety of products.'),
('PRET', 'Premium Textile Mills Limited', 'TEXTILE SPINNING', 'Premium Textile Mills Limited operates in the textile spinning industry, producing a variety of textile products for different market segments.'),
('PRIB', 'Prudential Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Prudential Investment Bank Limited is engaged in investment banking and securities services, providing financial solutions and services to clients.'),
('PRIC', 'Progressive Insurance Company Limited', 'INSURANCE', 'Progressive Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('PRL', 'Pakistan Refinery Limited', 'REFINERY', 'Pakistan Refinery Limited is involved in the refinery industry, processing crude oil and producing refined petroleum products.'),
('PRWM', 'Prosperity Weaving Mills Limited', 'TEXTILE WEAVING', 'Prosperity Weaving Mills Limited operates in the textile weaving industry, producing a variety of woven fabrics.'),
('PSEL', 'Pakistan Services Limited', 'MISCELLANEOUS', 'Pakistan Services Limited operates in the miscellaneous sector, involved in various business activities.'),
('PSMC', 'Pak Suzuki Motor Company Limited', 'AUTOMOBILE ASSEMBLER', 'Pak Suzuki Motor Company Limited is a major player in the automobile assembler industry, manufacturing and marketing Suzuki vehicles.'),
('PSO', 'Pakistan State Oil Company Limited', 'OIL & GAS MARKETING COMPANIES', 'Pakistan State Oil Company Limited is involved in the oil and gas marketing industry, providing fuel and lubricants to consumers and businesses.'),
('PSX', 'Pakistan Stock Exchange Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Pakistan Stock Exchange Limited operates in the investment banks, investment companies, and securities companies sector, facilitating stock trading and investment activities.'),
('PSYL', 'Pakistan Synthetics Limited', 'SYNTHETIC & RAYON', 'Pakistan Synthetics Limited operates in the synthetic and rayon industry, producing synthetic and rayon products.'),
('PTC', 'Pakistan Telecommunication Company Ltd', 'TECHNOLOGY & COMMUNICATION', 'Pakistan Telecommunication Company Ltd is a major player in the technology and communication industry, providing telecommunication services to individuals and businesses.'),
('PTL', 'Panther Tyres Ltd.', 'AUTOMOBILE PARTS & ACCESSORIES', 'Panther Tyres Ltd. operates in the automobile parts and accessories industry, manufacturing and supplying tires and related products.'),
('PUDF', 'Prudential Stocks Fund Limited', 'CLOSE - END MUTUAL FUND', 'Prudential Stocks Fund Limited operates as a close-end mutual fund, investing in a diversified portfolio of stocks and securities.'),
('QUET', 'Quetta Textile Mills Limited', 'TEXTILE COMPOSITE', 'Quetta Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('QUICE', 'Quice Food Industries Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Quice Food Industries Limited operates in the food and personal care products industry, producing a variety of products.'),
('RCML', 'Reliance Cotton Spinning Mills Limited', 'TEXTILE SPINNING', 'Reliance Cotton Spinning Mills Limited operates in the textile spinning industry, producing cotton yarn and related products.'),
('REDCO', 'Redco Textiles Limited', 'TEXTILE COMPOSITE', 'Redco Textiles Limited operates in the textile composite industry, producing a variety of textile products.'),
('REGAL', 'Regal Ceramics Limited', 'GLASS & CERAMICS', 'Regal Ceramics Limited operates in the glass and ceramics industry, manufacturing and supplying ceramics products.'),
('REWM', 'Reliance Weaving Mills Limited', 'TEXTILE COMPOSITE', 'Reliance Weaving Mills Limited operates in the textile composite industry, producing a variety of woven and dyed fabrics.'),
('RICL', 'Reliance Insurance Company Limited', 'INSURANCE', 'Reliance Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('RMPL', 'Rafhan Maize Products Company Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Rafhan Maize Products Company Limited operates in the food and personal care products industry, producing a variety of products.'),
('RPL', 'Roshan Packages Limited', 'PAPER & BOARD', 'Roshan Packages Limited operates in the paper and board industry, manufacturing and providing packaging solutions.'),
('RUBY', 'Ruby Textile Mills Limited', 'TEXTILE SPINNING', 'Ruby Textile Mills Limited operates in the textile spinning industry, producing a variety of textile products.'),
('RUPL', 'Rupali Polyester Limited', 'SYNTHETIC & RAYON', 'Rupali Polyester Limited operates in the synthetic and rayon industry, producing synthetic yarn and related products.'),
('SAIF', 'Saif Textile Mills Limited', 'TEXTILE SPINNING', 'Saif Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn and textile products.'),
('SANE', 'Salman Noman Enterprises Limited', 'TEXTILE SPINNING', 'Salman Noman Enterprises Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SANSM', 'Sanghar Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Sanghar Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SAPT', 'Sapphire Textile Mills Limited', 'TEXTILE COMPOSITE', 'Sapphire Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('SARC', 'Sardar Chemical Industries Limited', 'CHEMICAL', 'Sardar Chemical Industries Limited operates in the chemical industry, producing a variety of chemical products.'),
('SASML', 'Sindh Abadgars Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Sindh Abadgars Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SAZEW', 'Sazgar Engineering Works Limited', 'AUTOMOBILE ASSEMBLER', 'Sazgar Engineering Works Limited operates in the automobile assembler industry, manufacturing and marketing automotive products.'),
('SBL', 'Samba Bank Limited', 'COMMERCIAL BANKS', 'Samba Bank Limited is engaged in the commercial banking sector, providing a range of banking and financial services.'),
('SCBPL', 'Standard Chartered Bank (Pak) Ltd', 'COMMERCIAL BANKS', 'Standard Chartered Bank (Pakistan) Ltd is a major player in the commercial banking sector, providing a range of banking and financial services.'),
('SCHT', 'Schon Textiles Limited', 'TEXTILE COMPOSITE', 'Schon Textiles Limited operates in the textile composite industry, producing a variety of textile products.'),
('SCL', 'Shield Corporation Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Shield Corporation Limited operates in the food and personal care products industry, producing a variety of products.'),
('SDOT', 'Sadoon Textile Industries Limited', 'TEXTILE WEAVING', 'Sadoon Textile Industries Limited operates in the textile weaving industry, producing a variety of woven fabrics.'),
('SEARL', 'The Searle Company Limited', 'PHARMACEUTICALS', 'The Searle Company Limited is involved in the pharmaceuticals industry, manufacturing and marketing pharmaceutical products.'),
('SEL', 'Sitara Energy Limited', 'POWER GENERATION & DISTRIBUTION', 'Sitara Energy Limited is engaged in the power generation and distribution sector, generating and supplying electricity.'),
('SEPL', 'Security Papers Limited', 'PAPER & BOARD', 'Security Papers Limited operates in the paper and board industry, producing a variety of paper and board products.'),
('SERT', 'Service Industries Textiles Limited', 'TEXTILE SPINNING', 'Service Industries Textiles Limited operates in the textile spinning industry, producing a variety of yarn and textile products.'),
('SFAT', 'Safa Textiles Limited', 'TEXTILE COMPOSITE', 'Safa Textiles Limited operates in the textile composite industry, producing a variety of textile products.'),
('SFL', 'Sapphire Fibres Limited', 'TEXTILE COMPOSITE', 'Sapphire Fibres Limited operates in the textile composite industry, producing a variety of textile products.'),
('SGABL', 'SG.Allied Businesses Limited', 'SYNTHETIC & RAYON', 'SG.Allied Businesses Limited operates in the synthetic and rayon industry, producing synthetic and rayon products.'),
('SGF', 'Service GlobalFootwear Limited', 'LEATHER & TANNERIES', 'Service GlobalFootwear Limited operates in the leather and tanneries industry, manufacturing and marketing footwear products.'),
('SGPL', 'S.G. Power Limited', 'POWER GENERATION & DISTRIBUTION', 'S.G. Power Limited is engaged in the power generation and distribution sector, generating and supplying electricity.'),
('SHCI', 'Shaffi Chemical Industries Limited', 'CHEMICAL', 'Shaffi Chemical Industries Limited operates in the chemical industry, producing a variety of chemical products.'),
('SHCM', 'Shadman Cotton Mills Limited', 'TEXTILE SPINNING', 'Shadman Cotton Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SHDT', 'Shadab Textile Mills Limited', 'TEXTILE SPINNING', 'Shadab Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SHEL', 'Shell Pakistan Limited', 'OIL & GAS MARKETING COMPANIES', 'Shell Pakistan Limited is involved in the oil and gas marketing industry, providing fuel and lubricants to consumers and businesses.'),
('SHEZ', 'Shezan International Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Shezan International Limited operates in the food and personal care products industry, producing a variety of products.'),
('SHFA', 'Shifa International Hospitals Limited', 'MISCELLANEOUS', 'Shifa International Hospitals Limited operates in the miscellaneous sector, providing healthcare and hospital services.'),
('SHJS', 'Shahtaj Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Shahtaj Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SHNI', 'Shaheen Insurance Company Limited', 'INSURANCE', 'Shaheen Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('SHSML', 'Shahmurad Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Shahmurad Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SIBL', 'Security Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Security Investment Bank Limited operates in the investment banks, investment companies, and securities companies sector, providing financial services and investment solutions.'),
('SICL', 'Standard Insurance Company Limited', 'INSURANCE', 'Standard Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('SIEM', 'Siemens (Pakistan) Engineering', 'CABLE & ELECTRICAL GOODS', 'Siemens (Pakistan) Engineering operates in the cable and electrical goods industry, manufacturing and providing electrical and electronic products.'),
('SILK', 'Silkbank Limited', 'COMMERCIAL BANKS', 'Silkbank Limited is engaged in the commercial banking sector, providing a range of banking and financial services.'),
('SINDM', 'Sindh Modaraba', 'MODARABAS', 'Sindh Modaraba operates as a modaraba, providing Islamic financial and investment services.'),
('SITC', 'Sitara Chemical Industries Limited', 'CHEMICAL', 'Sitara Chemical Industries Limited operates in the chemical industry, producing a variety of chemical products.'),
('SKRS', 'Sakrand Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Sakrand Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SLCL', 'Security Leasing Corporation Limited', 'LEASING COMPANIES', 'Security Leasing Corporation Limited operates in the leasing companies sector, providing leasing and financial services.'),
('SLCPA', 'Security Leasing Corp.9.10%(Pref)', 'LEASING COMPANIES', 'Security Leasing Corp.9.10%(Pref) operates in the leasing companies sector, providing leasing and financial services.'),
('SLL', 'SME Leasing Limited', 'LEASING COMPANIES', 'SME Leasing Limited operates in the leasing companies sector, providing leasing and financial services.'),
('SLYT', 'Sally Textile Mills Limited', 'TEXTILE SPINNING', 'Sally Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SMBL', 'Summit Bank Limited', 'COMMERCIAL BANKS', 'Summit Bank Limited is engaged in the commercial banking sector, providing a range of banking and financial services.'),
('SMCPL', 'Safe Mix Concrete Limited', 'CEMENT', 'Safe Mix Concrete Limited operates in the cement industry, producing and supplying ready-mix concrete.'),
('SML', 'Shakarganj Limited', 'SUGAR & ALLIED INDUSTRIES', 'Shakarganj Limited operates in the sugar and allied industries, producing sugar and related products.'),
('SNAI', 'Sana Industries Limited', 'TEXTILE SPINNING', 'Sana Industries Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SNBL', 'Soneri Bank Limited', 'COMMERCIAL BANKS', 'Soneri Bank Limited is engaged in the commercial banking sector, providing a range of banking and financial services.'),
('SNGP', 'Sui Northern Gas Pipelines Limited', 'OIL & GAS MARKETING COMPANIES', 'Sui Northern Gas Pipelines Limited is involved in the oil and gas marketing industry, distributing natural gas to consumers and businesses.'),
('SPEL', 'Synthetic Products Enterprises Limited', 'MISCELLANEOUS', 'Synthetic Products Enterprises Limited operates in the miscellaneous sector, producing a variety of synthetic and plastic products.'),
('SPL', 'Sitara Peroxide Limited', 'CHEMICAL', 'Sitara Peroxide Limited operates in the chemical industry, producing hydrogen peroxide and other chemical products.'),
('SPLC', 'Saudi Pak Leasing Company Limited', 'LEASING COMPANIES', 'Saudi Pak Leasing Company Limited operates in the leasing companies sector, providing leasing and financial services.'),
('SPWL', 'Saif Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Saif Power Limited is engaged in the power generation and distribution sector, generating and supplying electricity.'),
('SRVI', 'Service Industries Limited', 'LEATHER & TANNERIES', 'Service Industries Limited operates in the leather and tanneries industry, manufacturing and marketing leather and related products.'),
('SSGC', 'Sui Southern Gas Company Limited', 'OIL & GAS MARKETING COMPANIES', 'Sui Southern Gas Company Limited is involved in the oil and gas marketing industry, distributing natural gas to consumers and businesses.'),
('SSIC', 'Silver Star Insurance Company Limited', 'INSURANCE', 'Silver Star Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('SSML', 'Saritow Spinning Mills Limited', 'TEXTILE SPINNING', 'Saritow Spinning Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SSOM', 'S.S.Oil Mills Limited', 'VANASPATI & ALLIED INDUSTRIES', 'S.S.Oil Mills Limited operates in the vanaspati and allied industries, producing cooking oil and related products.'),
('STCL', 'Shabbir Tiles & Ceramics Limited', 'GLASS & CERAMICS', 'Shabbir Tiles & Ceramics Limited operates in the glass and ceramics industry, producing a variety of tiles and ceramics products.'),
('STJT', 'Shahtaj Textile Limited', 'TEXTILE WEAVING', 'Shahtaj Textile Limited operates in the textile weaving industry, producing a variety of woven fabrics.'),
('STML', 'Shams Textile Mills Limited', 'TEXTILE COMPOSITE', 'Shams Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('STPL', 'Siddiqsons Tin Plate Limited', 'MISCELLANEOUS', 'Siddiqsons Tin Plate Limited operates in the miscellaneous sector, producing tin plate and related products.'),
('SUHJ', 'Suhail Jute Mills Limited', 'JUTE', 'Suhail Jute Mills Limited operates in the jute industry, manufacturing and marketing jute products.'),
('SURAJ', 'Suraj Ghee Industries Limited', 'VANASPATI & ALLIED INDUSTRIES', 'Suraj Ghee Industries Limited operates in the vanaspati and allied industries, producing ghee and related products.'),
('SURC', 'Suraj Cotton Mills Limited', 'TEXTILE COMPOSITE', 'Suraj Cotton Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('SUTM', 'Sunrays Textile Mills Limited', 'TEXTILE SPINNING', 'Sunrays Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('SYM', 'Symmetry Group Limited', 'TECHNOLOGY & COMMUNICATION', 'Symmetry Group Limited operates in the technology and communication industry, providing a range of technology solutions and services.'),
('SYS', 'Systems Limited', 'TECHNOLOGY & COMMUNICATION', 'Systems Limited operates in the technology and communication industry, providing a range of technology solutions and services.'),
('SZTM', 'Shahzad Textile Mills Limited', 'TEXTILE SPINNING', 'Shahzad Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('TAJT', 'Taj Textile Mills Limited', 'TEXTILE COMPOSITE', 'Taj Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('TATM', 'Tata Textile Mills Limited', 'TEXTILE SPINNING', 'Tata Textile Mills Limited operates in the textile spinning industry, producing a variety of yarn products.'),
('TBL', 'Treet Battery Limited.', 'AUTOMOBILE PARTS & ACCESSORIES', 'Treet Battery Limited is engaged in the automobile parts and accessories industry, manufacturing and marketing batteries.'),
('TCORP', 'Tariq Corporation Limited', 'SUGAR & ALLIED INDUSTRIES', 'Tariq Corporation Limited operates in the sugar and allied industries, producing sugar and related products.'),
('TCORPCPS', 'Tariq Corporation Limited(Pref)', 'SUGAR & ALLIED INDUSTRIES', 'Tariq Corporation Limited(Pref) operates in the sugar and allied industries, producing sugar and related products.'),
('TELE', 'Telecard Limited', 'TECHNOLOGY & COMMUNICATION', 'Telecard Limited operates in the technology and communication industry, providing a range of communication services and solutions.'),
('TGL', 'Tariq Glass Industries Limited', 'GLASS & CERAMICS', 'Tariq Glass Industries Limited operates in the glass and ceramics industry, producing glass containers and tableware.'),
('THALL', 'Thal Limited', 'AUTOMOBILE PARTS & ACCESSORIES', 'Thal Limited is involved in the automobile parts and accessories industry, manufacturing and marketing automotive and engineering products.'),
('THCCL', 'Thatta Cement Company Limited', 'CEMENT', 'Thatta Cement Company Limited operates in the cement industry, producing and selling cement products.'),
('TICL', 'The Thal Industries Corporation Limited', 'SUGAR & ALLIED INDUSTRIES', 'The Thal Industries Corporation Limited operates in the sugar and allied industries, producing sugar and related products.'),
('TOMCL', 'The Organic Meat Company Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'The Organic Meat Company Limited operates in the food and personal care products industry, providing organic meat products.'),
('TOWL', 'Towellers Limited', 'TEXTILE COMPOSITE', 'Towellers Limited operates in the textile composite industry, producing a variety of textile products.'),
('TPL', 'TPL Corp Limited', 'TECHNOLOGY & COMMUNICATION', 'TPL Corp Limited operates in the technology and communication industry, providing a range of technology solutions and services.'),
('TPLI', 'TPL Insurance Limited', 'INSURANCE', 'TPL Insurance Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('TPLP', 'TPL Properties Limited', 'PROPERTY', 'TPL Properties Limited operates in the property sector, involved in real estate development and management.'),
('TPLT', 'TPL Trakker Limited', 'TECHNOLOGY & COMMUNICATION', 'TPL Trakker Limited operates in the technology and communication industry, providing tracking and security solutions.'),
('TREET', 'Treet Corporation Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Treet Corporation Limited operates in the food and personal care products industry, manufacturing and marketing a variety of consumer products.'),
('TRG', 'TRG Pakistan Limited', 'TECHNOLOGY & COMMUNICATION', 'TRG Pakistan Limited operates in the technology and communication industry, providing business process outsourcing and technology solutions.'),
('TRIBL', 'Trust Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Trust Investment Bank Limited operates in the investment banking and securities industry, providing financial and investment services.'),
('TRIPF', 'Tri-Pack Films Limited', 'MISCELLANEOUS', 'Tri-Pack Films Limited operates in the miscellaneous sector, producing a range of packaging films and related products.'),
('TRSM', 'Trust Modaraba', 'MODARABAS', 'Trust Modaraba operates in the modarabas sector, providing financial and investment services.'),
('TSBL', 'Trust Securities & Brokerage Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.', 'Trust Securities & Brokerage Limited operates in the investment banking and securities industry, providing brokerage and investment services.'),
('TSMF', 'Tri-Star Mutual Fund Limited', 'CLOSE - END MUTUAL FUND', 'Tri-Star Mutual Fund Limited operates as a closed-end mutual fund, managing investment portfolios for investors.'),
('TSML', 'Tandlianwala Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES', 'Tandlianwala Sugar Mills Limited operates in the sugar and allied industries, producing sugar and related products.'),
('TSPL', 'Tri-Star Power Limited', 'POWER GENERATION & DISTRIBUTION', 'Tri-Star Power Limited is engaged in the power generation and distribution sector, generating and supplying electricity.'),
('UBDL', 'United Brands Limited', 'MISCELLANEOUS', 'United Brands Limited operates in the miscellaneous sector, involved in the marketing and distribution of consumer products.'),
('UBL', 'United Bank Limited', 'COMMERCIAL BANKS', 'United Bank Limited is a commercial bank, providing a range of banking and financial services.'),
('UBLPETF', 'UBLPakistan Enterprise ETF', 'EXCHANGE TRADED FUNDS', 'UBLPakistan Enterprise ETF is an exchange-traded fund (ETF) that tracks the performance of companies in the Pakistan enterprise sector.'),
('UCAPM', 'Unicap Modaraba', 'MODARABAS', 'Unicap Modaraba operates in the modarabas sector, providing financial and investment services.'),
('UDPL', 'United Distributors Pakistan Limited', 'MISCELLANEOUS', 'United Distributors Pakistan Limited operates in the miscellaneous sector, involved in the distribution of consumer products.'),
('UNIC', 'The United Insurance Company', 'INSURANCE', 'The United Insurance Company is engaged in the insurance industry, providing a range of insurance products and services.'),
('UNITY', 'Unity Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Unity Foods Limited operates in the food and personal care products industry, manufacturing and marketing a variety of consumer products.'),
('UPFL', 'Unilever Pakistan Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'Unilever Pakistan Foods Limited operates in the food and personal care products industry, manufacturing and marketing a range of consumer products.'),
('USMT', 'Usman Textile Mills Limited', 'TEXTILE COMPOSITE', 'Usman Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('UVIC', 'The Universal Insurance Company Limited', 'INSURANCE', 'The Universal Insurance Company Limited is engaged in the insurance industry, providing a range of insurance products and services.'),
('WAHN', 'Wah Noble Chemicals Limited', 'CHEMICAL', 'Wah Noble Chemicals Limited operates in the chemical industry, producing a variety of chemical products.'),
('WAVES', 'Waves Corporation Limited', 'CABLE & ELECTRICAL GOODS', 'Waves Corporation Limited operates in the cable and electrical goods industry, manufacturing and marketing a range of electrical and electronic products.'),
('WAVESAPP', 'Waves Home Appliances Limited', 'CABLE & ELECTRICAL GOODS', 'Waves Home Appliances Limited operates in the cable and electrical goods industry, manufacturing and marketing home appliances and electronics.'),
('WTL', 'Worldcall Telecom Limited', 'TECHNOLOGY & COMMUNICATION', 'Worldcall Telecom Limited operates in the technology and communication industry, providing a range of telecommunication services and solutions.'),
('YOUW', 'Yousaf Weaving Mills Limited', 'TEXTILE WEAVING', 'Yousaf Weaving Mills Limited operates in the textile weaving industry, producing a variety of woven fabrics.'),
('ZAHID', 'Zahidjee Textile Mills Limited', 'TEXTILE COMPOSITE', 'Zahidjee Textile Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('ZELP', 'Zeal Pak Cement Factory Limited', 'CEMENT', 'Zeal Pak Cement Factory Limited operates in the cement industry, producing and selling cement products.'),
('ZHCM', 'Zahur Cotton Mills Limited', 'TEXTILE COMPOSITE', 'Zahur Cotton Mills Limited operates in the textile composite industry, producing a variety of textile products.'),
('ZIL', 'ZIL Limited', 'FOOD & PERSONAL CARE PRODUCTS', 'ZIL Limited operates in the food and personal care products industry, manufacturing and marketing a range of consumer products.'),
('ZTL', 'Zephyr Textiles Limited', 'TEXTILE WEAVING', 'Zephyr Textiles Limited operates in the textile weaving industry, producing a variety of woven fabrics.');

